from g4f import Client
from pypdf import PdfReader
from uuid import UUID
import base64
import io
import re
class CandidateMatcher:
    candidateId: UUID
    firstName: str
    lastName: str
    skills: str
    experienceYears: int
    educationLevel: str
    cvBase64: str
    cvContent: str
    cvFilePath: str
    recommendationBase64: str
    certificatesBase64: list
    additionalContent: str
    score: float
    reasoning: str

    def __init__(self, candidateId: UUID, firstName: str, lastName: str, skills: str, experienceYears: int, educationLevel: str, cvBase64: str, cvContent: str, cvFilePath: str, recommendationBase64: str = "", certificatesBase64: list = None):
        self.candidateId = candidateId
        self.firstName = firstName
        self.lastName = lastName
        self.skills = skills
        self.experienceYears = experienceYears
        self.educationLevel = educationLevel
        self.cvBase64 = cvBase64
        self.cvContent = cvContent
        self.cvFilePath = cvFilePath
        self.recommendationBase64 = recommendationBase64
        self.certificatesBase64 = certificatesBase64 if certificatesBase64 is not None else []
        self.additionalContent = ""
        self.score = 0.0
        self.reasoning = ""

    def compute_score(self, jobDescription: str):
        client = Client()
        systemPrompt = "You are an expert HR specialist evaluating a candidate's suitability for a job based on their skills, experience, education, their cv, recommendation letters, and certificates compared to the job description. The score must be from 0 to 100 (float). Your output should exactly be under this format : 'SCORE: x.xx | REASON: Detailed and professional reasoning clearly linking their specific skills or experience to the job requirements.'"
        prompt = f"Job Description: {jobDescription}\n\nCandidate Skills: {self.skills}\nExperience: {self.experienceYears} years\nEducation: {self.educationLevel}\nCV Content: {self.cvContent}\nAdditional Documents (Recommendations/Certificates): {self.additionalContent}\n\nRate the candidate's suitability for the job on a scale of 1 to 100, where 1 means not suitable at all and 100 means perfectly suitable."
        
        try:
            response = client.chat.completions.create(
                model="gpt-3.5-turbo", 
                messages=[{"role": "system", "content": systemPrompt}, {"role": "user", "content": prompt}]
            )
            content = response.choices[0].message.content.strip()
            match = re.search(r'SCORE:\s*([\d.]+)', content)
            self.score = float(match.group(1)) if match else 0.0
            reason_match = re.search(r'REASON:\s*(.+)', content)
            self.reasoning = reason_match.group(1).strip() if reason_match else "Score generated by AI."
        except Exception as e:
            # Fallback mock scoring if AI service is blocked or fails
            exp_years = self.experienceYears or 0
            # Be generous to competent candidates in fallback
            base_score = 45.0
            
            # Up to 35 points for experience (caps at 7 years for max points)
            score_from_exp = min(exp_years * 5.0, 35.0)
            
            # 20 points explicitly for having a parseable CV
            score_from_cv = 20.0 if (self.cvContent and len(self.cvContent) > 20) else 0.0
            
            total_score = base_score + score_from_exp + score_from_cv
            self.score = min(total_score, 100.0)
            
            if self.score > 85.0:
                qualifier = "Excellent match."
            elif self.score > 70.0:
                qualifier = "Strong candidate."
            else:
                qualifier = "Needs review."
            self.reasoning = f"Based on strict formula calculation due to AI timeout: {qualifier} Candidate possesses {exp_years} years of documented experience with an attached resume."

    def get_cv_content(self):
        """Decode base64 CV and extract plain text using pypdf.
        Falls back to reading directly from cvFilePath if cvBase64 is not set."""
        try:
            if self.cvBase64:
                pdf_bytes = base64.b64decode(self.cvBase64)
                reader = PdfReader(io.BytesIO(pdf_bytes))
            elif self.cvFilePath:
                reader = PdfReader(self.cvFilePath)
            else:
                self.cvContent = ""
                return
            pages_text = []
            for page in reader.pages:
                text = page.extract_text()
                if text:
                    pages_text.append(text)
            self.cvContent = "\n".join(pages_text)
        except Exception as e:
            self.cvContent = f"[Could not extract CV text: {e}]"

    def get_additional_documents_content(self):
        """Decode base64 for recommendation letters and certificates and extract text."""
        texts = []
        
        # Recommendation
        if self.recommendationBase64:
            try:
                pdf_bytes = base64.b64decode(self.recommendationBase64)
                reader = PdfReader(io.BytesIO(pdf_bytes))
                rec_text = " ".join([page.extract_text() for page in reader.pages if page.extract_text()])
                if rec_text:
                    texts.append("RECOMMENDATION LETTER:\n" + rec_text)
            except Exception as e:
                texts.append(f"[Could not extract Recommendation Letter: {e}]")
                
        # Certificates
        for idx, cert_b64 in enumerate(self.certificatesBase64):
            try:
                pdf_bytes = base64.b64decode(cert_b64)
                reader = PdfReader(io.BytesIO(pdf_bytes))
                cert_text = " ".join([page.extract_text() for page in reader.pages if page.extract_text()])
                if cert_text:
                    texts.append(f"CERTIFICATE {idx+1}:\n" + cert_text)
            except Exception as e:
                texts.append(f"[Could not extract Certificate {idx+1}: {e}]")
                
        self.additionalContent = "\n\n".join(texts)



        