services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: grh-postgres
    environment:
      POSTGRES_DB: GRHDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kameless1925
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - grh-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.3
    container_name: grh-keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: kameless1925
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - grh-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "exec 3<>/dev/tcp/127.0.0.1/8080; echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3; if grep -q '200 OK' <&3; then exit 0; else exit 1; fi",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s

  # Spring Boot Application
  grh-app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: grh-backend
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATABASE_URL: jdbc:postgresql://postgres:5432/GRHDb
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: kameless1925
      JWT_SECRET: zx1EsZszdTNaMTD9R19ig+veDflBGyXTNwlO0Q4RRLrl/eYW6MzIIYnRRb2OnEr31GsiKFtX5p7z8K3XSp+qCA==
      JWT_EXPIRATION: 86400000
      JPA_SHOW_SQL: false
      JPA_FORMAT_SQL: false
      FLYWAY_ENABLED: true
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    networks:
      - grh-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8081/actuator/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  grh-network:
    driver: bridge
